export const AvailableBlogCategory = [
  { label: "Artificial Intelligence", value: "artificial-intelligence" },
  { label: "Machine Learning", value: "machine-learning" },
  { label: "Data Science", value: "data-science" },
  { label: "Big Data", value: "big-data" },
  { label: "Blockchain", value: "blockchain" },
  { label: "Cryptocurrency", value: "cryptocurrency" },
  { label: "Cloud Computing", value: "cloud-computing" },
  { label: "Cybersecurity", value: "cybersecurity" },
  { label: "Internet of Things", value: "internet-of-things" },
  { label: "Augmented Reality", value: "augmented-reality" },
  { label: "Virtual Reality", value: "virtual-reality" },
  { label: "Mixed Reality", value: "mixed-reality" },
  { label: "Quantum Computing", value: "quantum-computing" },
  { label: "Software Development", value: "software-development" },
  { label: "Web Development", value: "web-development" },
  { label: "Mobile Development", value: "mobile-development" },
  { label: "Game Development", value: "game-development" },
  { label: "DevOps", value: "devops" },
  { label: "Agile Methodologies", value: "agile-methodologies" },
  { label: "Data Structures", value: "data-structures" },
  { label: "Algorithms", value: "algorithms" },
  { label: "Competitive Programming", value: "competitive-programming" },
  { label: "Programming Languages", value: "programming-languages" },
  { label: "JavaScript", value: "javascript" },
  { label: "Python", value: "python" },
  { label: "Java", value: "java" },
  { label: "C#", value: "c-sharp" },
  { label: "C++", value: "c-plus-plus" },
  { label: "Ruby", value: "ruby" },
  { label: "PHP", value: "php" },
  { label: "Swift", value: "swift" },
  { label: "Kotlin", value: "kotlin" },
  { label: "Go", value: "go" },
  { label: "Rust", value: "rust" },
  { label: "TypeScript", value: "typescript" },
  { label: "HTML & CSS", value: "html-css" },
  { label: "React", value: "react" },
  { label: "Angular", value: "angular" },
  { label: "Vue.js", value: "vue-js" },
  { label: "Svelte", value: "svelte" },
  { label: "Node.js", value: "node-js" },
  { label: "Django", value: "django" },
  { label: "Flask", value: "flask" },
  { label: "Spring Boot", value: "spring-boot" },
  { label: "ASP.NET", value: "asp-net" },
  { label: "Laravel", value: "laravel" },
  { label: "Ruby on Rails", value: "ruby-on-rails" },
  { label: "Microservices", value: "microservices" },
  { label: "API Development", value: "api-development" },
  { label: "Database Management", value: "database-management" },
  { label: "SQL", value: "sql" },
  { label: "NoSQL", value: "nosql" },
  { label: "MongoDB", value: "mongodb" },
  { label: "PostgreSQL", value: "postgresql" },
  { label: "MySQL", value: "mysql" },
  { label: "SQLite", value: "sqlite" },
  { label: "Firebase", value: "firebase" },
  { label: "GraphQL", value: "graphql" },
  { label: "RESTful APIs", value: "restful-apis" },
  { label: "Testing & QA", value: "testing-qa" },
  { label: "Unit Testing", value: "unit-testing" },
  { label: "Integration Testing", value: "integration-testing" },
  { label: "End-to-End Testing", value: "end-to-end-testing" },
  { label: "Automation Testing", value: "automation-testing" },
  { label: "CI/CD", value: "ci-cd" },
  { label: "Containerization", value: "containerization" },
  { label: "Docker", value: "docker" },
  { label: "Kubernetes", value: "kubernetes" },
  { label: "Serverless Architecture", value: "serverless-architecture" },
  { label: "Network Security", value: "network-security" },
  { label: "Ethical Hacking", value: "ethical-hacking" },
  { label: "Penetration Testing", value: "penetration-testing" },
  { label: "Digital Forensics", value: "digital-forensics" },
  { label: "Cryptography", value: "cryptography" },
  { label: "Information Security", value: "information-security" },
  { label: "Artificial Neural Networks", value: "artificial-neural-networks" },
  { label: "Natural Language Processing", value: "natural-language-processing" },
  { label: "Computer Vision", value: "computer-vision" },
  { label: "Reinforcement Learning", value: "reinforcement-learning" },
  { label: "Robotics", value: "robotics" },
  { label: "Automation", value: "automation" },
  { label: "Career Development", value: "career-development" },
  { label: "Freelancing", value: "freelancing" },
  { label: "Remote Work", value: "remote-work" },
  { label: "Tech Industry News", value: "tech-industry-news" },
  { label: "Startup Culture", value: "startup-culture" },
  { label: "Entrepreneurship", value: "entrepreneurship" },
  { label: "E-Learning", value: "e-learning" },
  { label: "Online Courses", value: "online-courses" },
  { label: "EdTech", value: "edtech" },
  { label: "Personal Finance", value: "personal-finance" },
  { label: "Investing", value: "investing" },
  { label: "Stock Market", value: "stock-market" },
  { label: "Real Estate", value: "real-estate" },
  { label: "Passive Income", value: "passive-income" },
  { label: "Side Hustles", value: "side-hustles" },
];
